export * from "@/database/schema/aiMetadata";
export * from "@/database/schema/attendance";
export * from "@/database/schema/goals";
export * from "@/database/schema/lectureSlots";
export * from "@/database/schema/preferences";
export * from "@/database/schema/semester";
export * from "@/database/schema/settings";
export * from "@/database/schema/subjects";
export * from "@/database/schema/timetable";
